### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Sergei-Alekseev** [fjdogar/multicore_rom_helper#1] opened 2024-09-16 03:52 UTC
Hello.
Tried with gba files.
Files created and i can see them on the device, 
but doesn't start. Loading screen forever.
No hangs, i can press start+select and exit.
Multicore 010. 

loader: run file=/mnt/sda1/GBA/bin/gba;Castlevania - Aria of Sorrow.gba
corefile=/mnt/sda1/cores/gba/core_87000000
romfile=/mnt/sda1/ROMS/gba/Castlevania - Aria of Sorrow
loader: core loaded
loader: cache flushed
clear_bss: start=0x8711c368 end=0x87bf7b18
call_ctors: start=0x8710b564 end=0x8710b564
loader: retro_init
config_load: /mnt/sda1/cores/config/gpSP.opt loaded
loader: run_emulator(0)
core=gpSP-v0.91 need_fullpath=1 exts=gba|bin|agb|gbz|u1
core loads content directly from file
[core][INFO] [Environ]: GET_VARIABLE: gpsp_drc=enabled
[core][INFO] [Environ]: GET_VARIABLE: gpsp_bios=official
[core][INFO] [Environ]: GET_VARIABLE: gpsp_boot_mode=game
[core][INFO] [Environ]: GET_VARIABLE: gpsp_frameskip=auto
[core][INFO] [Environ]: GET_VARIABLE: gpsp_frameskip_threshold=33
[core][INFO] [Environ]: GET_VARIABLE: gpsp_frameskip_interval=3
support for auto frameskipping enabled
[core][INFO] [Environ]: GET_VARIABLE: gpsp_color_correction=disabled
[core][INFO] [Environ]: GET_VARIABLE: gpsp_frame_mixing=disabled
[core][INFO] [Environ]: GET_VARIABLE: gpsp_save_method=gpSP
[core][INFO] [Environ]: GET_VARIABLE: gpsp_turbo_period=4
[core][INFO] [Environ]: SAVE_DIRECTORY: "/mnt/sda1/ROMS/save"
[core][INFO] [Environ]: SYSTEM_DIRECTORY: "/mnt/sda1/bios"
[core][ERROR] [gpSP]: Could not load the game file.
retro_load_game failed
loader: retro_deinit

/GBA/bin/gba is not existed

**Comment by fjdogar** [comment] 2024-09-16 14:23
Thanks for pointing out the bug with detailed log.
i am guessing something broke while switch to pyqt ui. I am reviewing the code , will be fixed soon.

**Comment by fjdogar** [comment] 2024-09-16 19:42
the issue is fixed in the new release

**Closed as completed by fjdogar** 2024-09-16 19:42 UTC
